# Configuration for actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

source:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'lib/**'
          - '**/*.ts'
          - '**/*.js'
          - '**/*.py'
          - '**/*.rs'
          - '**/*.go'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'
          - 'tests/**'
          - '**/*.test.ts'
          - '**/*.spec.ts'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
